# This script is run when the server is called and is designed to house 
# all of the static information that is used by the app
# setwd("shiny")

# Packages ----------------------------------------------------------------

library(shiny)
library(shinyjs)
library(dplyr)
library(readr)
library(lubridate)
library(magrittr)
library(leaflet)
library(leaflet.extras)
library(raster)
library(rgdal)
library(DT)
library(shinyBS)
library(heatwaveR)
library(tidyr)
library(plotly)
# library(mapview)
library(ncdf4)
# library(dygraphs)

#slackr
# slackr::slackr_setup(config_file = "./.slackr")

# source('functions.R', local = TRUE)
# poisson_logo <- actionLink(inputId = 'poisson', 
#                            label = img(src = 'poisson-logo.png',
#                                        height = 177/5,
#                                        width = 739/5,
#                                        onclick = "window.open('http://www.poissonconsulting.ca', '_blank')"))


# Modules -----------------------------------------------------------------

source('modules/about-server.R', local = TRUE)
source('modules/about-ui.R', local = TRUE)
source('modules/map-server.R', local = TRUE)
source('modules/map-ui.R', local = TRUE)

### ui vars
# proj.description <- "Display tidal predictions generated by the rtide R package."
# proj <- "U.S. Tidal Predictions"

# mapbox_moon <- "https://api.mapbox.com/styles/v1/sebpoisson/cjjfvxsqh1nrd2rnqabh10sx4/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1Ijoic2VicG9pc3NvbiIsImEiOiJjamk1YXBiYm4waHd0M2twNmM3ODRuZjN4In0.WKHsGJ3K7SWyqO4lObCkfA
# "
# disclaimer <- "Important disclaimer: Tide predictions are generated using the rtide R package and are not suitable for navigation.
# For more information about rtide, visit the"


# Meta-data ---------------------------------------------------------------

initial_lat <- 43
initial_long <- -120
initial_zoom <- 3
click_zoom <- 11
leaf.pos <- "topright"
sidepanel.width <- 400

# The lon/lat steps
load("lon_OISST.RData")
lat_OISST <- seq(-89.875, 89.875, by = 0.25)

# palette <- c('#07A8FF', "#FFBA00", "#FF3900")
# shades <- c("#4EC0FD", "#1FB1FF", "#0091DF", "00649A")
# marker <- makeIcon(
#   iconUrl = "input/marker.png",
#   iconWidth = 30, iconHeight = 30
# )
# sites <- readRDS('input/sites.rds')

# appCSS <- ".mandatory_star { color: red; }"

# The event categories
# load("MHW_cat_clim.RData")
# MHW_cat_clim_sub_sub <- MHW_cat_clim_sub %>% 
#   select(category) %>% 
#   distinct()

MHW_cat_clim_sub <- data.frame(category = c("I Moderate", "II Strong", "III Severe", "IV Extreme"))

# The indexed NetCDF database
OISST_index <- data.frame(file_name = dir(path = "OISST", pattern = "avhrr", full.names = T),
                          lon = lon_OISST[1:length(dir(path = "OISST", pattern = "avhrr", full.names = T))])
thresh_index <- data.frame(file_name = dir(path = "thresh", full.names = T),
                           lon = lon_OISST[1:length(dir(path = "OISST", pattern = "avhrr", full.names = T))])

# The category colour pallette
MHW_colours <- c(
  "I Moderate" = "#ffc866",
  "II Strong" = "#ff6900",
  "III Severe" = "#9e0000",
  "IV Extreme" = "#2d0000"
)
# MHW_colours <- data.frame(val = c("#ffc866", "#ff6900", "#9e0000", "#2d0000"),
#                           label = c("I Moderate", "II Strong", "III Severe", "IV Extreme"))

# Colour palettes for different metrics etc.
pal_factor <- colorFactor(palette = MHW_colours, levels = levels(MHW_cat_clim_sub$category))
# pal_factor <- colorFactor(palette = MHW_colours$val, domain = MHW_colours$label)
pal_cat <- colorNumeric(palette = MHW_colours, domain = c(1,2,3,4), na.color = NA)

# previewColors(colorFactor(palette = MHW_colours$val, domain = MHW_colours$label), MHW_cat_clim_sub)

# Establish projection choices
inputProj <- "+init=epsg:4326 +proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"
leafletProj <- "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +nadgrids=@null +wktext +no_defs"

# The base map
# map_base <- ggplot2::fortify(maps::map(fill = TRUE, plot = FALSE)) %>% 
#   dplyr::rename(lon = long) %>% 
#   # filter(lat >= 25.6) %>%
#   mutate(group = ifelse(lon > 180, group+9999, group),
#          lon = ifelse(lon > 180, lon-360, lon)) %>% 
#   group_by(group)
# 
# saveRDS(map_base, "map_base.Rda")

# Placeholder xy before first click
# xy <- data.frame(lng = 0, lat = 0)